'use strict';

/**
 * Our actions will act like a semantic helper
 * method which sends the payload generated by a
 * view to the dispatcher in a way the our
 * stores will know how to deal with later.
 */

var AppDispatcher = require('../dispatcher/AppDispatcher');
var TodoConstants = require('../constants/TodoConstants');

var TodoActions = {
  // `create` will be triggered whenever there's a
  // `need to create something (i.e., add new
  // `stuff) to put in our store.
  create (text) {
    AppDispatcher.handleViewAction({
      actionType: TodoConstants.TODO_CREATE,
      text: text
    });
  },

  // destroy a specific item
  destroy (id) {
    AppDispatcher.handleViewAction({
      actionType: TodoConstants.TODO_DESTROY,
      id: id
    });
  },

  // destroy all of the items marked as complete
  destroyCompleted () {
    AppDispatcher.handleViewAction({
      actionType: TodoConstants.TODO_DESTROY_COMPLETED,
    });
  },

  // toggles complete all
  toggleCompleteAll () {
    AppDispatcher.handleViewAction({
      actionType: TodoConstants.TODO_TOGGLE_COMPLETE_ALL,
    });
  }
};

module.exports = TodoActions;
